apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: fit-forge
  labels:
    app: user-service
type: Opaque
stringData:
  MONGO_URI: "mongodb://user_user:utMYP6wGPZ2ORVx5VTkf1IG%2BIFWSSalZ@mongodb-0.mongodb-headless.fit-forge.svc.cluster.local:27017,mongodb-1.mongodb-headless.fit-forge.svc.cluster.local:27017,mongodb-2.mongodb-headless.fit-forge.svc.cluster.local:27017/user_db?replicaSet=rs0"
  JWT_SECRET: "4mZ_8xK2vW9uL_Qp5rN7yB3eT1hG6sJ9aC0dXzM_fVv"
