name: CI — Frontend
on:
  push:
    branches: 
      - develop
      - main
    paths:
      - "services/frontend-service/**"
      - ".github/workflows/ci-frontend-service.yml"
      - ".github/workflows/_ci-template.yml"
  pull_request:
    branches:
      - develop
      - main
    paths:
      - "services/frontend-service/**"
      - ".github/workflows/ci-frontend-service.yml"
      - ".github/workflows/_ci-template.yml"
jobs:
  ci:
    uses: ./.github/workflows/_ci-template.yml
    with:
      service-name: frontend-service
      service-path: services/frontend-service
      runtime: node
      node-version: "20"
      environment: ${{ github.ref_name }}
    secrets: inherit