apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-user-update
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: mongo-client
          image: mongo:7.0
          command:
            - /bin/sh
            - -c
            - |
              mongosh "mongodb://mongo-0.mongo-service.default.svc.cluster.local:27017" \
                --username "$MONGO_INITDB_ROOT_USERNAME" \
                --password "$MONGO_INITDB_ROOT_PASSWORD" \
                --authenticationDatabase admin \
                --eval '
                  db = db.getSiblingDB("auth_db");
                  if (!db.getUser("auth_user")) {
                    db.createUser({
                      user: "auth_user",
                      pwd: "AuthPass@3",
                      roles: [{ role: "readWrite", db: "auth_db" }]
                    });
                  }
                '
          envFrom:
            - secretRef:
                name: mongo-root-secret