apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
provisioner: cluster.local/dev-nfs-provisioner-nfs-subdir-external-provisioner
# When the PVC is deleted, data is also deleted
reclaimPolicy: Delete
parameters:
  # How dir should be created
  pathPattern: "rnld-${.PVC.namespace}-${.PVC.name}"
  # Works only when "reclaimPolicy: Delete" to delete the sub-directories
  onDelete: delete